# Generated by Django 5.0.6 on 2024-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_watering_options_alter_watering_date_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='tools',
            field=models.ManyToManyField(to='main_app.tool'),
        ),
    ]
